### ISSUE TITLE
perf(lexer): Use SIMD to accelerate whitespace skipping

### ISSUE THREAD

**Issue by Boshen** [Boshen/oxc#13]
Sometime ago I drafted a version to use SIMD for skipping whitespaces:

![image](https://user-images.githubusercontent.com/1430279/218290188-5cbcff19-ca62-48aa-960e-1c1bc060464f.png)

In this good first issue, you should be able to replicate the code from above, and add it to the lexer.

You should refactor the code above into a function and call the function just above the while loop:

https://github.com/Boshen/oxc/blob/93993978de969589f1fb91a689594a5e5c4b8f02/crates/oxc_parser/src/lexer/mod.rs#L320-L330

You will also need to add `#![feature(portable_simd)]` to the top of `crates/oxc_parser/src/lib.rs`

To the run parser, you can run the example binary:

https://github.com/Boshen/oxc/blob/3daf5bcea95f6fe2c88a7956948f4cb22711f99e/crates/oxc_parser/examples/simple.rs#L7-L10

Background reading:
* https://rapidjson.org/md_doc_internals.html#SkipwhitespaceWithSIMD
* https://github.com/Tencent/rapidjson/blob/bdc49ad80a3cff89a25839dcdcd6a68b457ec9f1/include/rapidjson/reader.h#L258-L517
* https://lemire.me/blog/2017/01/20/how-quickly-can-you-remove-spaces-from-a-string

**Comment by ematipico** [comment]
Adding also a beginner introduction, taken from the rust repository: https://github.com/rust-lang/portable-simd/blob/master/beginners-guide.md
