### ISSUE TITLE
perf(lexer): keyword match using phf

### ISSUE THREAD

**Issue by Boshen** [Boshen/oxc#165]
@YangchenYe323 @YoniFeng Let's continue our adventure after the video https://www.youtube.com/watch?v=DMQ_HcNSOAI

@YangchenYe323 Can you draft a baseline line PR, and let's walk up the performance ladder. We don't need to go all the way.

**Comment by Boshen** [comment]
@YangchenYe323 can you accept the repo invite and push branch into this repo, for making it easier for us to work together.

**Comment by YangchenYe323** [comment]
> @YangchenYe323 can you accept the repo invite and push branch into this repo, for making it easier for us to work together.

Got it.
