### ISSUE TITLE
perf(cli/lint) poor print performance above several hundred diagnostics threshold

### ISSUE THREAD

**Issue by YoniFeng** [Boshen/oxc#166]
**Problem**
Printing lint errors slows down exponentially.
Slowness is significant once the threshold of a few hundred diagnostics is crossed.

**Repro**
1. Download [babylon.max.js](https://cdn.jsdelivr.net/npm/babylonjs@4.2.1/babylon.max.js) (arbitrary example)
2. Build release
3. Run `./oxc_cli.exe lint --max-warnings 1 babylon.max.js` - very fast E2E time (to give an idea of parsing time)
4. Run `./oxc_cli.exe lint --max-warnings 10 babylon.max.js` - E2E time barely increased.
5. Run `./oxc_cli.exe lint --max-warnings 100 babylon.max.js` - E2E time increased much more in relative terms. On my machine, it's ~60x, where the number of printed messages only grew 10x (90 vs 9).
6. Run `./oxc_cli.exe lint --max-warnings 500 babylon.max.js` - time 20x,
7. You get the point..

**Initial findings**
I thought it would be related to writing to stdout, but that seems to be done correctly already:
```rust
 let mut buf_writer = BufWriter::new(std::io::stdout());
        let mut number_of_warnings = 0;
        let mut number_of_diagnostics = 0;

        while let Ok(diagnostic) = rx_error.recv() {
            number_of_diagnostics += 1;

            if diagnostic.severity() == Some(Severity::Warning) {
                number_of_warnings += 1;
                // The --quiet flag follows ESLint's --quiet behavior as documented here: https://eslint.org/docs/latest/use/command-line-interface#--quiet
                // Note that it does not disable ALL diagnostics, only Warning diagnostics
                if self.cli_options.quiet {
                    continue;
                }

                if let Some(max_warnings) = self.cli_options.max_warnings {
                    if number_of_warnings > max_warnings {
                        continue;
                    }
                }
            }

            buf_writer
                .write_all(format!("{diagnostic:?}").as_bytes())
                .expect("Failed to write diagnostic.");
        }
```

One thing we can improve is take the lock on `stdout`. However, that doesn't solve the issue.

Profiling shows all of the time spent in `miette`:
![image](https://user-images.githubusercontent.com/32789876/224484422-13d76be4-aee0-47e2-8c84-42e3bd4a779d.png)

The culprit isn't immediately obvious.
I haven't dug into miette code yet. It seems unlikely that it would have such a big performance issue, with no smoke (I couldn't find any issues in the repo related to performance).

The exponential nature of the slowness hints towards some vector or other struct's memory not being cleared/reused efficiently.

**Comment by Boshen** [comment]
I think I know why ... it's reallocating the 10MB file for every label, which blows the the memory allocator. The `Arc` is a lie ... I thought miette should be is zero-copy, or at least just allocate a small part.

We should be able to fix this by grouping the diagnostics into this `related` field. https://docs.rs/miette/latest/miette/index.html#-multiple-related-errors

**Comment by Boshen** [comment]
Wrong, it's not about memory, it's about scanning the whole file for every label

https://github.com/zkat/miette/blob/c857595e1ae689028c5c5b66148e81b175eaa509/src/source_impls.rs#L28

**Comment by Boshen** [comment]
To fix this, I think we need to implement our own `SourceCode` with caching.

**Comment by YoniFeng** [comment]
Ok, I hope I'm not missing anything. (Feeling a little dizzy).
My understanding is as follows:

The issue is indeed the miette has to iterate through the whole source code every time.
If we don't (and won't ever) require having before/after context lines, I _think_ fixing this shouldn't be too big of a deal. We'll have our own SourceCode implementation (`read_span()`) where we always make the offset start at 0, and provide a str slice that starts at that offset. (e.g. instead of giving a file's full source code and offset (1000, 1010) we'd give &source[1000..] and offset (0, 10)).
However, once there's even a single rule that needs before/after context lines, it'll be a problem.

**We can also just ignore this issue**. It only surfaces for ridiculously large files.
It's reasonable to assume/expect source files don't go over 1-2MB. Even that's obscene.. do you know of a project that has such a thing? the largest single source file I'm aware of is (non-JS/TS) [.NET's gc.cpp](https://github.com/dotnet/runtime/blob/main/src/coreclr/gc/gc.cpp).

**Comment by Boshen** [comment]
> We can also just ignore this issue

I vote for ignore 😁

**Comment by zkat** [comment]
You can probably fix this by having a SourceCode implementation that uses `.seek()`!
