### ISSUE TITLE
feat(diagnostics): better diagnostics for language/asi/S7.9_A6.3_T1.js

### ISSUE THREAD

**Issue by Fnll** [Boshen/oxc#176]
for test of test262/test/language/asi/S7.9_A6.3_T1.js
```ts
for(
) {
  break;
}
```
oxc now only prints `Unexpected token` for `for` loop statements  missing expressions.
```
  × Unexpected token
    ╭─[language/asi/S7.9_A6.3_T1.js:19:1]
 19 │ for(
 20 │ ) {
    · ─
 21 │   break;
    ╰────
```
It would be better to print `expression expected`.

**Comment by Fnll** [comment]
Sure, please assign it to me

**Comment by Boshen** [comment]
Unassign due to inactivity.
