### ISSUE TITLE
trait `VisitMut`

### ISSUE THREAD

**Issue by magic-akari** [Boshen/oxc#184]
Would it be advisable to introduce `VisitMut` for the purpose of applying AST transformations?

**Comment by Boshen** [comment]
Is this for working with the transpiler?

**Comment by magic-akari** [comment]
> Is this for working with the transpiler?

Yes, I am trying to transpile JSX.

**Comment by Boshen** [comment]
@magic-akari Done.

To setup this up, you need to bring in the allocator and `AstBuilder`.

**Comment by magic-akari** [comment]
I need something like `visit_mut_children_with` in SWC or something `super.visit_expression()` in OOP.

<img width="681" alt="image" src="https://user-images.githubusercontent.com/7829098/226183421-69631011-3f6c-4850-8ee3-7df0f819355e.png">

**Comment by Boshen** [comment]
If this doesn't work:

https://github.com/Boshen/oxc/blob/b0ce6e41584a2066b6f241d1b68ce7a37adb15d8/crates/oxc_ast/src/visit_mut.rs#L334-L338

I guess we'll need to implement it like rustc https://doc.rust-lang.org/stable/nightly-rustc/rustc_ast/visit/trait.Visitor.html

Just very boring code :-)

**Comment by magic-akari** [comment]
> If this doesn't work (use `visit_expression_match`):
> 
> https://github.com/Boshen/oxc/blob/b0ce6e41584a2066b6f241d1b68ce7a37adb15d8/crates/oxc_ast/src/visit_mut.rs#L334-L338
> 
> I guess we'll need to implement it like rustc https://doc.rust-lang.org/stable/nightly-rustc/rustc_ast/visit/trait.Visitor.html
> 
> Just very boring code :-)

Ah! `visit_expression_match` works!

What an ingenious approach!
Do you have a crystal ball🔮 to predict this usage?

**Comment by Boshen** [comment]
> Do you have a crystal ball🔮 to predict this usage?

Just simple mind reading 😉
