### ISSUE TITLE
feat(parser): stage 3 decorators 

### ISSUE THREAD

**Issue by Boshen** [Boshen/oxc#187]
There are a few stage 3 decorators not being parsed right now:

https://github.com/Boshen/oxc/blob/326de5006bb9d2a8368cdf6ea9c58558bd9ced7c/tasks/coverage/test262.snap#L36-L104

**Comment by YangchenYe323** [comment]
I'd like to work on this one.

**Comment by YangchenYe323** [comment]
```
 43 │ var C = @ns.$
    ·         ─
 44 │ @ns._
```
I'm wondering what is the expected AST here? (a). Assignment of decorator to variable. (b). Assignment of identifier(or member function?) to variable (seems unlikely) (c). Eaten decorators and assign nothing to C.

**Comment by Boshen** [comment]
Lol this is wild, it took me a minute to figure this out.

So here's the process:
1. open the test262 file https://github.com/tc39/test262/blob/main/test/language/expressions/class/decorator/syntax/valid/decorator-member-expr-decorator-member-expr.js
2. stare at the comments
3. stare at the description "description: Decorator @ DecoratorMemberExpression (Valid syntax for decorator on class expression)"
4. scroll to the the bottom of the file and see `@ns.await class {};`
5. 💡

**Comment by Boshen** [comment]
Here's the change in the grammar

https://github.com/tc39/proposal-decorators -> https://arai-a.github.io/ecma262-compare/?pr=2417

<img width="1029" alt="image" src="https://user-images.githubusercontent.com/1430279/225491705-bf7d7284-56ef-4816-81cf-76648190101f.png">

**Comment by YangchenYe323** [comment]
Oh I got it! Thanks for the grammar compare site. It's super helpful.
