### ISSUE TITLE
bug(linter): not all rules are running

### ISSUE THREAD

**Issue by YoniFeng** [Boshen/oxc#206]
While looking into #166, I noticed linting a file filled with `new Array();` resulted in 0 lint errors.

**Initial finding**
Setting a breakpoint in `no_array_constructor`'s `run()`, it never gets called.

I removed all rules except `no_array_constructor` from `declare_all_lint_rules!`.
Setting a breakpoint on the linter's `run` (in 'oxc_linter/src/lib.rs'), `self.rules` has size 0.

Need to keep looking - maybe the macro screws up?

**Comment by Boshen** [comment]
https://github.com/Boshen/oxc/blob/5ae3f5e0071931548f4206a19c60af9c5d12f416/crates/oxc_linter/src/lib.rs#L47

I filtered it out for now because I want to showcase correctness rules. I'm still undecided on all the other rule categories.
