### ISSUE TITLE
feat(linter): array-callback-return

### ISSUE THREAD

**Issue by Boshen** [Boshen/oxc#218]
>  How to implement array-callback-return?
> My naive idea is to traverse all the paths and color them.
> Can the visitor design pattern be used to achieve this?

_Originally posted by @magic-akari in https://github.com/Boshen/oxc/issues/216#issuecomment-1485073419_

----

There are three components to implementing this:
1. Search for functions - AST check
2. Get the array method name by looking at parent node - AST check
3. Search the descents of AST node by either:
  * Use the Visitor trait
  * Use [descendants](https://docs.rs/indextree/latest/indextree/struct.NodeId.html#method.descendants) from indextree
  * Mark the function with `HasImplicitReturn` and `HasExplicitReturn` inside the semantic analyzer - you can find these in the TypeScript.
  
I'm pretty liberal on these methods, try whatever that creates the least noise.

**Comment by YangchenYe323** [comment]
It seems to me that such lint are easier and more natural to implement on a Control Flow Graph (e.g., check all the exit block of a CFG). Eslint implements a code path analysis which is similar to CFG. Would you prefer we doing something similar in oxc or stick with an AST approach?

**Comment by Boshen** [comment]
> It seems to me that such lint are easier and more natural to implement on a Control Flow Graph (e.g., check all the exit block of a CFG). Eslint implements a code path analysis which is similar to CFG. Would you prefer we doing something similar in oxc or stick with an AST approach?

Yes a CFG the best approach, my suggestions are workarounds. 

I wonder what kind of CFG we should write? @YangchenYe323 are you familiar or studied it? I ported the one from TypeScript before but it was super painful to work with. The one in ESLint or Rome seems to be more manageable.

> Mark the function with HasImplicitReturn and HasExplicitReturn inside the semantic analyzer - you can find these in the TypeScript.

This is something fun to study in the TypeScript codebase, it's only used in like two places, but it has some very large impact.

**Comment by YangchenYe323** [comment]
> Yes a CFG the best approach, my suggestions are workarounds.
> 
> I wonder what kind of CFG we should write? @YangchenYe323 are you familiar or studied it? I ported the one from TypeScript before but it was super painful to work with. The one in ESLint or Rome seems to be more manageable.

I don't know how to do it yet. Might need to learn how eslint does the code-path analysis. 



> Mark the function with HasImplicitReturn and HasExplicitReturn inside the semantic analyzer - you can find these in the TypeScript.

I tried an implementation in similar vein in #221 , though it's lazily called by the rule now. I'll have a look into how typescript does it. I feel that my approach is kind of complex...

**Comment by Boshen** [comment]
I opened a discussion on CFG, https://github.com/Boshen/oxc/discussions/222

You can edit or add a new comment.

**Comment by Boshen** [comment]
Closed by #221
