### ISSUE TITLE
feat(semantic): node -> symbol lookup

### ISSUE THREAD

**Issue by Boshen** [Boshen/oxc#225]
Currently there's no method for look up a symbol from a `BindingIdentifier` / `IdentifierReference` inside the linter.

The minifier also need this for the printer to print mangled names.

One possible solution is to create an index for a `Span` -> `SymbolId` lookup.

I wonder we should make an overhaul on the Symbol Table. I had no idea what I was doing when I wrote the symbol table, and I wrote whatever is sensible.

**Comment by YangchenYe323** [comment]
When working on #247 I found that the extra hashing steps make the semantic builder 10x slower. Is it an option to remove the hashing altogether and store an additional `SymbolId`with BindingIdentifier and `ReferenceId` with `IdentifierReference`?
