### ISSUE TITLE
feat(linter): `no-bitwise` rule

### ISSUE THREAD

**Issue by mysteryven** [Boshen/oxc#227]
Implement the ESLint [no-bitwise](https://eslint.org/docs/latest/rules/no-bitwise) rule.

~~refer to bad-bitwise-operator in https://github.com/Boshen/oxc/issues/123.~~

**Comment by Boshen** [comment]
It seems we have a misunderstanding here,

[`bad-bitwise-operator`](https://deepscan.io/docs/rules/bad-bitwise-operator) is from deepscan, where it forbids bitwise in certain constructs.
[`no-bitwsise`](https://eslint.org/docs/latest/rules/no-bitwise) is for forbidding all bitwise operations.

This is why `bad-bitwise-operator` can be categoriezed as correctness. And `no-bitwsise` is not a recommended rule in ESLint.

I'll update the list so it's clearer.

**Comment by mysteryven** [comment]
Okay, I'll close this PR and find another task suitable for me 😀

**Comment by Boshen** [comment]
The deepscan rules are not that hard, you just have to come up with the test cases yourself ;-)

**Comment by Boshen** [comment]
Reopen because we can this merge and put this under nursery, I'll promote this to pedantic in the future.

**Comment by mysteryven** [comment]
> The deepscan rules are not that hard, you just have to come up with the test cases yourself ;-)

I am interested in it, I will try to tackle it after finish this rule.

**Comment by Boshen** [comment]
closed by #228
