### ISSUE TITLE
Panics when testing files

### ISSUE THREAD

**Issue by qarmin** [Boshen/oxc#232]
```
oxc_cli lint all .
```
crashes with such messages

```
thread 'main' panicked at 'byte index 21 is not a char boundary; it is inside '\u{ae3a6}' (bytes 18..22) of `  static async * #򮎦W_‌_NJ(value) {`', crates/oxc_diagnostics/src/graphic_reporter.rs:599:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error', crates/oxc_cli/src/lint/runner.rs:171:70
```

Broken files - [Broken_138.zip](https://github.com/Boshen/oxc/files/11124044/Broken_138.zip)

**Comment by Boshen** [comment]
Thank you for trying out oxc! It's probably a unicode line ending `\u{2028}` or `\u{2029}` in one of the TypeScript files. Real code don't use unicode line endings so I neglected them 😅 

One of the source code lookup is broken:

https://github.com/Boshen/oxc/blob/main/crates/oxc_linter/src/disable_directives.rs#L96

**Comment by Boshen** [comment]
I tested the latest release (v0.0.4) and it all passed without panics.

`npx oxidation-compiler@latest lint .`

**Comment by qarmin** [comment]
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error', crates/oxc_cli/src/lint/runner.rs:171:70
```
```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', crates/oxc_parser/src/lib.rs:228:44
```
Command `oxc_cli lint -A all a.js --fix`

[Broken_355.zip](https://github.com/Boshen/oxc/files/11160287/Broken_355.zip)

**Comment by Boshen** [comment]
@qarmin Can you try the latest version  (v0.0.5) `npx oxidation-compiler@latest lint .`
