### ISSUE TITLE
feat(linter): no-constant-condition

### ISSUE THREAD

**Issue by mysteryven** [Boshen/oxc#258]
Implement ESLint [no-constant-condition](https://eslint.org/docs/latest/rules/no-constant-condition) rule.

Hopefully finish it this week.

**Comment by Boshen** [comment]
A few pointers:
* the [isConstant](https://github.com/eslint/eslint/blob/cf682d249f04a6a304407d5b9ddbbc4a9714dd62/lib/rules/utils/ast-utils.js#L888) seems easy to export
* `checkLoops` needs cfg or some other logic in the semantic analyzer, you can omit it for now
* https://github.com/Boshen/oxc/blob/6fca02298206d1ab5f516bfd4d5674348834f580/crates/oxc_linter/src/context.rs#L147-L149 is currently blank, @YangchenYe323 should be able to help out

**Comment by YangchenYe323** [comment]
> * https://github.com/Boshen/oxc/blob/6fca02298206d1ab5f516bfd4d5674348834f580/crates/oxc_linter/src/context.rs#L147-L149
>    is currently blank, @YangchenYe323 should be able to help out

It's actually a very non-trivial task. There's no simple way to go from a raw `IdentifierReference` to its semantic information, which are stored and indexed with `AstNodes`. 

To preserve this interface we need to store additional information in `IdentifierReference`, or we'd have to operate on `AstNodes` for these sort of tasks.

**Comment by mysteryven** [comment]
I found it's a little annoying to migrate ESLint test files when I implement this rule, so I wrote a [simple tool](https://github.com/mysteryven/eslint-test-case-to-oxc). Maybe it's useful for simple test file.(I tested him with only a few rules, It just works now, perhaps I can refine it when migrating the later ones 😹😹)

**Comment by Boshen** [comment]
Ahh .. it's my fault to not document `cargo rule` command from `tasks/rulegen` 😢 

I should also document `.cargo/config.toml` because it has alias commands.

**Comment by mysteryven** [comment]
Wow, it's such a great tool! Never mind this, maybe I'm the only one who missed it, and I have learned a new point in Rust. What's more, this tool still works for me, my command line can't download by HTTP client due to the network and can only use `curl` to get the GitHub resources, It's strange :).

**Comment by Boshen** [comment]
> my command line can't download by HTTP client

Is it talking about `vendored-openssl`? Or are you using Clash?

**Comment by mysteryven** [comment]
> Or are you using Clash?

I am using Clash, and I have copied the shell command to my terminal.

**Comment by Boshen** [comment]
> > Or are you using Clash?
> 
> I am using Clash, and I have copied the shell command to my terminal.

Let me call IT service for my sponsor. @Dreamacro have you seen this before? He can only curl but not through any http client with Clash.

**Comment by Dreamacro** [comment]
@mysteryven 

Using environment variables to make commands proxy is not a good choice.

Environment variables work only if the command itself reads them and uses them, but from a real-world perspective, most command line tool does not comply with this.

If you are using ClashX, then just download a ClashX Pro and turn on "Enhanced Mode", other than that, just open the TUN-like mode.

**Comment by mysteryven** [comment]
> If you are using ClashX, then just download a ClashX Pro and turn on "Enhanced Mode", other than that, just open the TUN-like mode.

Thank you so much, this problem has been bothering me for a long time, and now it is finally solved!

**Comment by Boshen** [comment]
@Dreamacro Thank you ❤️
