### ISSUE TITLE
refactor(semantics): Better Semantic Tree structure

### ISSUE THREAD

**Issue by YangchenYe323** [Boshen/oxc#260]
# Problem Description

Currently we reference syntactic AST nodes directly in the semantic AST nodes:
https://github.com/Boshen/oxc/blob/6fca02298206d1ab5f516bfd4d5674348834f580/crates/oxc_semantic/src/node/mod.rs#L17-L25

This means if we are given an `AstNode` referring to a `BinaryExpression` and want to find its left operand, there are two ways to do so:
1.
```rust
let AstKind::BinaryExpression(expr) = node.get().kind();
expr.left
// We've lost the AstNode wrapping this expression and all the semantic information associated with the node
```
2.
```rust
// Hard-coded fact that the left child node is the first child of the binary expression node
let left_id = node.first_child().unwrap()
arena[left_id]
```

Using the first approach loses track of the semantic tree node wrapping the syntactic node, which poses a problem, for example, when we want to get reference/symbol information. 

The second approach is hard to program with and maintain consistency. It tightly couples with the way we visit the Syntactic AST to build the semantic tree. 

# Proposed Solution

Implement a separate tree structure for semantic tree rather than referencing syntactic tree node directly. For example, a semantic tree's BinaryExpression could be:

```rust
struct BinaryExpression {
  span: Span,
  operator: BinaryOperator,
  left: SemanticNodeId, // The key difference: now we get another SemanticTreeNode through the left field
  right: SemanticNodeId,
}

enum SemanticNodeKind {
  BinaryExpr(BinaryExpression)
}

struct SemanticTreeNode {
  kind: SemanticNodeKind,
  parent: Option<SemanticNodId>,
  // All associated semantic information
  scope_info,
  symbol_info,
  reference_info,
}

struct SemanticTree {
  arena: Arena<SemanticTreeNode> // indexed by SemanticNodeId
  program: SemanticNodeId,
}
```

This is related to my comment in #258 When implementing lint rules there're often two kinds of needs: 1. look up something based on the `AstNode`. 2. Traverse the tree structurally. Currently the life is hard if we want to do 1 and 2 at the same time, looking up something while traversing.

A corollary is that we will no longer rely on `indextree` to track the parent-child relations for us, just need an arena to store all the nodes. A bumpalo based vector can do the job, too. We could promise to never garbage collect nodes to save some space for the ID stucture.

**Comment by Boshen** [comment]
A few thoughts:
* This looks like CST going backwards
* We'll have to re-declare all the ast nodes, which is huge
* We still want to work on the AST because it's simple
* I think this construction should become our HIR for scope / cfg / symbol resolution
* Can we add an "ast node id" in the parser so we can reference between these representations? HIR has its own ID https://doc.rust-lang.org/beta/nightly-rustc/rustc_hir/hir_id/struct.HirId.html

I still like the direction for this, let's explore more.

**Comment by Boshen** [comment]
> Can we add an "ast node id" 

I seriously considered this before, but at that time using `Span` for lookups worked for the linter. But I think it's not going to work when things get complicated, because you can get the same span for two different nodes.

e.g. On this `ObjectExpression` `({ a })`, `key` and `value` have the same span.

```
              "key": {
                "type": "IdentifierName",
                "start": 3,
                "end": 4,
                "name": "a"
              },
              "value": {
                "type": "IdentifierReference",
                "start": 3,
                "end": 4,
                "name": "a"
              },
```

**Comment by Boshen** [comment]
Do you think we should just add a `Span` -> `Symbol` or `NodeId` lookup to unblock people for now, and then focus on the bigger picture?

**Comment by YangchenYe323** [comment]
> * We still want to work on the AST for the linter because it's simple

I think you're right on this. In the old AST the left hand side of `AssignmentExpression` is an `AssignmentTarget`, but in the new tree it would be just another `SemanticNodeKind`. 

> * Can we add an "ast node id" in the parser so we can reference between these representations?
> * We'll have to re-declare all the ast nodes, which is huge

Combining these points, should we directly augment the `IdentifierReference` and other syntactic AST types?  For example 
```rust
struct IdentifierReference {
  span: Span,
  name: Atom,
  #[serde(skip)]
  ast_node_id,
  #[serde(skip)]
  reference_id,
}
```
Then in the semantic builder pass we can directly modify the AST to fill in these pieces. `Span` -> `Symbol` or `NodeId ` lookup is also reasonable to me, though I'm worried it slows things down too much. In #247 I tried building several indexes in the semantic pass, and the performance degradation is horrible I have no clue...

### Further thought on HIR

If we're introducing another representation I would hope it to be a canonical representation for transform passes. On second thought, I don't think my proposed construct can do this job...

Closure compiler has a DeadAssignmentElimination pass, where it needs to replace an arbitrary assignment node (we know that it is an Assignment but its parent could be anything) with its right hand side (could also be anything). For example:
`foo((x = 1))` becomes `foo(1)`, and `return (x = 123) + b` becomes `return 123 + b`

I think our current AST and the construct I proposed are still both difficult to handle these tasks, because it is different to delete the child of a binary expression than to delete a child of a call expression. 

Closure compiler uses the IR of [rhino](https://github.com/mozilla/rhino), which is very like a node in indextree:

```
struct Node {
  data: Data // Differs for each AST Type
  next_sibling: &Node // siblings form a circular linked list
  prev_sibling: &Node
  first_child: &Node // children form a circular linked list
  last_child: &Node
  parent: &Node
}
```

In such an IR replacing an arbitrary node with another arbitrary node is easy as the difference between AST types are abstracted away.

**Comment by Boshen** [comment]
Here's my proposal:

1. Add the slow index lookup for `is_global_reference` to unlock people, assuming the public API for `Semantic` will roughly stay the same.
2. Build a prototype for the HIR + CFG for a tiny portion of the AST to test the water, probably in the following two weeks once we done enough research.

Further down the road, the linter will have a late pass on the HIR, just like how clippy has two separate passes.

What do you think?

**Comment by Boshen** [comment]
The idea for better semantic tree structure has been incorporated into the HIR.
