### ISSUE TITLE
Fix problem with parentheses inside minifier

### ISSUE THREAD

**Issue by Boshen** [Boshen/oxc#338]
Since the introduction of the HIR with the removal of the `ParenthesizedExpression`, the minifier's printer is now broken with lots tests (see https://github.com/Boshen/oxc/blob/main/tasks/coverage/minifier_test262.snap)

To fix these tests, we need to examine the failing tests and add back the parentheses. I have done an example in e753a88.

To get started:

* Copy a path from https://github.com/Boshen/oxc/blob/main/tasks/coverage/minifier_test262.snap
* Open up https://github.com/tc39/test262 and press `t` (or click go to file) and paste in the path
* copy test text to `test.js` and run `cargo watch -x 'run -p oxc_minifier --example minifier -- ./test.js'`
* Find the broken code and the relevant code in `crates/oxc_minifier/src/printer/gen.rs`
* fix the code and run `cargo coverage` and `cargo minsize`
* verify the test has been removed from `minifier_test262.snap`

**Comment by mysteryven** [comment]
I'd like to take this.😀

**Comment by Boshen** [comment]
You can also run `cargo watch -x "run -p oxc_ast_lower --example ast_lower` for printing the hir.

**Comment by Boshen** [comment]
All fixed.
