### ISSUE TITLE
feat: interpreterDirective (a.k.a `#!shebang`)

### ISSUE THREAD

**Issue by Boshen** [Boshen/oxc#429]
Oxc currently parses shebang as a comment, but we should change it to a dedicated ast node.

This will make the formatter / printer a little easier.

Steps:
* inside the lexer, modify 
https://github.com/Boshen/oxc/blob/9df154560298bb754efcd33aded89618e1490794/crates/oxc_parser/src/lexer/mod.rs#L423-L427
and let it return a dedicated token
* inside the ast, add a dedicated ast node to `Program`, see https://github.com/babel/babel/blob/d062d47d57a679953144ccf1e60b3efc297e5b43/packages/babel-parser/src/types.d.ts#L182
* inside the parser, consume the token and add the node to `Program`
* inside hir and ast_lower, copy this ast node to HIR
* inside the minifier, print the hashbang
* this test should pass in the end

https://github.com/Boshen/oxc/blob/9df154560298bb754efcd33aded89618e1490794/crates/oxc_minifier/tests/tdewolff/mod.rs#L7

**Comment by sno2** [comment]
I'd like to take this, please.
