### ISSUE TITLE
feat(parser): use scalar version of `skip_whitespace`for wasm

### ISSUE THREAD

**Issue by Boshen** [Boshen/oxc#435]
In wasm, we should not use https://github.com/Boshen/oxc/blob/main/crates/oxc_parser/src/lexer/simd.rs routines.

In places where we use these routines, we should swap it out with `#[cfg(target_arch = "wasm32")]`

For example, we should find the old `skip_whitespace` function from the git history and feature toggle it with `#[cfg(target_arch = "wasm32")]`.

**Comment by sno2** [comment]
I'll do this.
