### ISSUE TITLE
Make arrow function body easier to distinguish as single expression

### ISSUE THREAD

**Issue by kaleidawave** [Boshen/oxc#452]
Given the arrow expressions
```ts
a => a
```
and
```
a => {
   a;
}
```
The two bodies are both
```json
"body": {
  "type": "FunctionBody",
  "start": 30,
  "end": 38,
  "directives": [],
  "statements": [
    {
      "type": "ExpressionStatement",
      "start": 34,
      "end": 36,
      "expression": {
        "type": "IdentifierReference",
        "start": 34,
        "end": 35,
        "name": "a"
      }
    }
  ]
},
```

Which makes it hard to know whether the function returns `a` or `undefined` 😉. A sum type (such as my own [ExpressionOrBlock](https://docs.rs/ezno-parser/0.0.3/ezno_parser/expressions/arrow_function/enum.ExpressionOrBlock.html)) or some flag to know whether it is a block or expression would be useful 👍

**Comment by u9g** [comment]
You have to look outside the body, there’s a field expression: true/false that will tell you whether the body is immediately returned, see: https://boshen.github.io/oxc/playground/?code=ZgBuACgAKAApACAAPQA%2BACAAYgAsACAAKAApACAAPQA%2BACAAewAgAGIAOwAgAH0AKQA%3D

**Comment by kaleidawave** [comment]
Ah that makes sense. I missed it reading, probably needs a doc comment. Or maybe a new method `ArrowExpression::try_into_expression(): self -> Result<Expression, Vec<Statement>>`?

**Comment by Boshen** [comment]
Action: documentation.

I kind of did this on purpose to reduce boilerplate for ast visit when I was writing the linter.

**Comment by Boshen** [comment]
993c171547b44218dbe9d1d98ea0b259d0fec711

**Comment by kaleidawave** [comment]
Awesome! Hopefully it is now clearer to others
