### ISSUE TITLE
Feat(cli): Ignore files

### ISSUE THREAD

**Issue by Boshen** [Boshen/oxc#54]
https://eslint.org/docs/latest/use/command-line-interface#ignore-files

It would be the best if you submit a PR for each command.

Make a comment if you wish to tackle this, so I can assign this issue to you.

**Comment by jason89521** [comment]
I want to take this task, could you give me a try?

**Comment by Boshen** [comment]
There's gonna be some merge conflict due to the other PRs, you can figure out the code beforehand, and then clean it up once the other related PRs are merged.

**Comment by jason89521** [comment]
Ok, thanks!

**Comment by Boshen** [comment]
@jason89521 You can work on this now, the other PR has been merged.

**Comment by jason89521** [comment]
@Boshen  Does the `add_custom_ignore_filename` work for you? I added a `.eslintignore` file at root, but it still lint the files when I execute the command: `cargo run --bin oxc_cli lint *.js *.ts`.

The content of the .eslintignore file:

```
foo.js
bar.js
test.js

```

**Comment by Boshen** [comment]
> @Boshen Does the `add_custom_ignore_filename` work for you? I added a `.eslintignore` file at root, but it still lint the files when I execute the command: `cargo run --bin oxc_cli lint *.js *.ts`.
> 
> The content of the .eslintignore file:
> 
> ```
> foo.js
> bar.js
> test.js
> ```

I'll need to debug this, probably at late night tonight.

By the way, `*.js` is expanded by the shell, does it work if you wrap it in quotes? `'*.js'`

**Comment by jason89521** [comment]
I tried `cargo run --bin oxc_cli lint '*.js'`, but it still printed the following result.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/47748132/221753723-0a76df1d-e74f-4851-a983-367f15808fb0.png">
