### ISSUE TITLE
Feat(cli): support glob path

### ISSUE THREAD

**Issue by Boshen** [Boshen/oxc#55]
https://eslint.org/docs/latest/use/command-line-interface#run-the-cli

> npx eslint [options] [file|dir|glob]*

> Please note that when passing a glob as a parameter, it is expanded by your shell. The results of the expansion can vary depending on your shell, and its configuration. If you want to use node glob syntax, you have to quote your parameter

Make a comment if you wish to tackle this, so I can assign this issue to you.

**Comment by amitdahan** [comment]
Would love to take this one on!
