### ISSUE TITLE
Feat(linter): `declare_oxc_lint` proc_macro

### ISSUE THREAD

**Issue by Boshen** [Boshen/oxc#60]
Rules have metadata we want to access to, but it is tedious to implement a `RuleMeta` trait on every lint rule.

In this good first issue, we will follow the more difficult paths of following `rust-clippy`, e.g.

https://github.com/rust-lang/rust-clippy/blob/e1ac1332b668f584919aba86ad3e81f267251e9b/clippy_lints/src/almost_complete_range.rs#L11-L31

So we need to:

* add a `declare_oxc_lint` proc_macro crate
* define a `RuleMeta` trait
* hook up the `NoDebugger` Rule with the proc macro
* add some tests for this, maybe in the same file where the `RuleMeta` trait is.

The first prototype should probably just contain a name and a documentation. Other metadata can be added later.

See
* Rome https://github.com/rome/tools/blob/5c60450e016318c761590e883fa33d780491d08c/crates/rome_analyze/src/rule.rs#L83
* Ruff https://github.com/charliermarsh/ruff/blob/3179fc110d815d9b5cb9a3179bad6e1246a5bbf8/crates/ruff_macros/src/lib.rs#L29-L34
* Clippy https://github.com/rust-lang/rust-clippy/blob/master/declare_clippy_lint/src/lib.rs https://github.com/rust-lang/rust-clippy/blob/e1ac1332b668f584919aba86ad3e81f267251e9b/clippy_lints/src/almost_complete_range.rs#L11-L31

Drop a comment if you wish to tackle this, so I can assign this issue to you.

**Comment by YoniFeng** [comment]
@Boshen issue can be closed
