### ISSUE TITLE
implement lint rules

### ISSUE THREAD

**Issue by thepassle** [Boshen/oxc#61]
After I wrap up the work on https://github.com/Boshen/oxc/pull/57 it'd be great to try to implement some lint rules, do you have any particular rules in mind that you'd like implemented? 🙂

**Comment by Boshen** [comment]
I'm ironing out the details in https://github.com/Boshen/oxc/pull/59

It would be superb if you review the PR by commits, and question all the things that doesn't make sense or lack documentation.

Once we are satisfied with the result, I'll gather some lint rules that only require AST checks.

**Comment by thepassle** [comment]
I feel like I can follow along with most of the code there, as far as my understanding goes, it looks like you had to support trivia to the lexer/parser to be able to access those kind of information in the linting rule. I would have expected that some of those trivia (like single line comments and multi line comments) would have been AST nodes themself though?

Additionally, Im able to follow along on most of the config parsing/reading, but im not entirely grokken what the `from_json` fn on the `Rule` impl does exactly.

Also I should read up more on const fns it looks like lol 😄

**Comment by Boshen** [comment]
@thepassle You can try this one https://github.com/Boshen/oxc/issues/67

Also, if you feel like https://github.com/Boshen/oxc/pull/57 is getting out of hand, I can take it over if you don't mind.

**Comment by thepassle** [comment]
Cool, thanks!

I think I should be able to wrap up #57 some time today, had to attend to some irl things yesterday 🙂
