### ISSUE TITLE
feat(oxc_parser): handle typescript modifiers in a more unified way

### ISSUE THREAD

**Issue by YangchenYe323** [Boshen/oxc#66]
#### Description
Typescript modifiers, e.g., `abstract`, `public`, `declare`, can appear in arbitrary order and they can modify any kind of declarations, not only class. For example, `abstract const a = 1;` can produce a valid AST and the semantic analyzer would reject the code because `abstract` can only modify class declaration.

#### Expected Behavior
oxc_parser should be able to produce valid AST for these kinds of constructs

#### Are you planning on fix it.
Yes

**Comment by Boshen** [comment]
Done in https://github.com/Boshen/oxc/pull/75
