### ISSUE TITLE
feat(linter): implement `no-array-constructor`

### ISSUE THREAD

**Issue by Boshen** [Boshen/oxc#67]
This is going to be fun! 

We will be porting the `no-array-constructor` rule for JavaScript and TypeScript at the same time:

* https://eslint.org/docs/latest/rules/no-array-constructor
* https://typescript-eslint.io/rules/no-array-constructor

The goal of this task is to:

* iron out the details for implementing a rule
* draft a documentation for how to implement a rule
* nice to have - create a script to transform tests to our Rust, because it is going to be very time consuming to copy, paste and modify the tests

Your feedbacks will shape the future of this project.

I have also setup a [discord channel](https://discord.com/invite/9uXCAwqQZW) for quick communications.

Drop a comment if you wish to try this, so I can assign this issue to you.

**Comment by Boshen** [comment]
In this task you will also learn about the [`if-let-chains`](https://rust-lang.github.io/rfcs/2497-if-let-chains.html) unstable feature, which is awesome for writing lint rules. `cargo fmt` doesn't support this at the moment, but I think manual formatting here is fine.

**Comment by amitdahan** [comment]
Would love to take this one!
