### ISSUE TITLE
feat(linter): code fixes

### ISSUE THREAD

**Issue by Boshen** [Boshen/oxc#68]
Let's study this and implement it https://github.com/eslint/eslint/blob/main/lib/linter/source-code-fixer.js

**Comment by Boshen** [comment]
Let's study this and implement it https://github.com/eslint/eslint/blob/main/lib/linter/source-code-fixer.js

**Comment by jason89521** [comment]
Store the needed information to fix a rule in the `Rule` struct and then the linter fix those rules which has the fix information. according to the information. Is this approach a proper way to do the code fixes?

**Comment by Boshen** [comment]
@jason89521 Join our discord server for faster feedbacks, @shannonrothe has started looking at this.

**Comment by Boshen** [comment]
The basic infrastructure is done, who wants to try and port the tests and implement it without looking at the actual implementation?

https://github.com/eslint/eslint/blob/main/tests/lib/linter/source-code-fixer.js

**Comment by jason89521** [comment]
I would like to try this one.

**Comment by sladyn98** [comment]
Does this still require help, I would love to contribute

**Comment by Boshen** [comment]
@sladyn98 The codefix implementation itself has been implemented, but the infrastructure for applying code fixes is only partially done. The command `--fix` currently does nothing. It would be much appreciated if you can help out and make `--fix` work as intended, end to end wise.

**Comment by Boshen** [comment]
Thank you so much for working on this @jason89521! I did some manual testing and this works great!
