### ISSUE TITLE
README is not very helpful

### ISSUE THREAD

**Issue by vixalien** [Boshen/oxc#69]
Sorry if this may come out as rude. But I'm not a rust developer, I saw oxc on github explore feed, and wanted to try it out (you know, let it "oxidise" my javascript), but the README doesn't have those instructions.

Usually, one would like to include "Installation" and "Usage" headings to help new users learn how to use it...

**Comment by Boshen** [comment]
Thanks for checking out this project! I didn't know you can find this project on github explore.

Are you expecting a linter or prettier for your JavaScript?

Unfortunately this project is currently work in progress, which means oxc is unusable right now. We'll probably get a workable linter with a few rules implemented within a month or so.

I'll clearly state this in the README.

**Comment by vixalien** [comment]
Thank you. I understand that you are currently working on the internals so it's not very usable at the moment. thank you for making this and good luck!!
