### ISSUE TITLE
Better diagnostics for language/asi/S7.9_A6.2_T10.js

### ISSUE THREAD

**Issue by Fnll** [Boshen/oxc#81]
for test of test262/test/language/asi/S7.9_A6.2_T10.js
```
for(
    false
;) {
  break;
}
```

oxc now only prints `Unexpected token` for expressions missing semicolon. 
```
  × Unexpected token
    ╭─[language/asi/S7.9_A6.2_T1.js:19:1]
 19 │ for(;
 20 │ ) {
    · ─
 21 │   break;
    ╰────
```

It would be better for the diagnostics to print  `';' expected` since we are in a for loop. An insertion of semi will simply help complete the for statement. See diagnostics of [tsc](https://www.typescriptlang.org/play?#code/GYewTgFAUABHPAIYBsDOBTKBuAlDA3rDAEZjqIDWWUAvkA)

**Comment by Boshen** [comment]
Would you like to have a go and fix this? This seems pretty simple: https://github.com/microsoft/TypeScript/blob/main/src/compiler/parser.ts#L6783

You can also remove the `then` .. `transpose()` syntax, it's not really readable I think ...

**Comment by Fnll** [comment]
I'd give it a shot
